### ISSUE TITLE
Audio Playback: Allow display of audio waveform visualization

### ISSUE THREAD

**Issue by jasonkaplan79** [DarinaUsanova/playerVue#1]
Awesome project! Love that this player has all the controls needed for playback **and** is using Vue.js with the composition API. Can we allow display of audio waveform visualization?

Examples:
* https://codeacme17.github.io/1llest-waveform-vue/
* https://thom4parisot.github.io/vue-waveform-template/

**Comment by DarinaUsanova** [comment]
Hi!
Thanks a lot for your suggestion, but I would like to keep the design simple this time.
